SimulationTester: Signal.cpp ConstantSource.cpp SineSource.cpp RectSource.cpp PT2.cpp SignalFunctions.cpp SimulationTester.cpp
	g++ Signal.cpp ConstantSource.cpp SineSource.cpp RectSource.cpp PT2.cpp SignalFunctions.cpp SimulationTester.cpp -std=c++11 -Wall -o SimulationTester
